### ISSUE TITLE
Getting extra characters when pasting

### ISSUE THREAD

**Issue by robbiet480** [ChrisJohnsen/tmux-MacOSX-pasteboard#31]
I'm on Yosemite DP8. When `set-option -g default-command "/usr/local/bin/reattach-to-user-namespace -l zsh"` is set in `~/.tmux.conf` I see extra characters prefixed and suffixed to anything I copy. For example, `hello world` becomes `0~hello world~1`. Disabling reattach-to-user-namespace fixes this issue. I'm setting `$TERM` to `xterm-256color`. I only experience this in tmux, outside of tmux everything is fine. tmux version is 1.9a, reattach-to-user-namespace is 2.3.

Thanks!

**Comment by papertigers** [comment]
I have seen this too.  Reliably.

**Comment by robbiet480** [comment]
Since my last comment, i've seen this every so often, but closing my `tmux` quickly fixes it.

**Comment by jgluck** [comment]
This happens pretty often for me as well.

**Comment by kraj** [comment]
For me  bracketed paste mode is the problem. I am using latest nightly Build 2.9.20160122-nightly
once I type printf '\e[?2004l' into the terminal it restores to what it was. Usually it happens to me when I restore my sessions having lid of laptop off. Usually I ssh into a remote linux box and run tmux on that server. Ssh from mac/iterm and work. Sometime I just close the lid and when I reopen thats what I see in iterm. My sessions to remote box are ofcourse disconnected.

**Comment by jseakle** [comment]
I experienced this issue specifically when ssh'd to certain servers, and `printf '\e[?2004l'` solved it!

**Comment by root42** [comment]
I also have this problem. Running tux 1.9 from Debian via ssh in vanilla OS X terminal. The printf fix did not work for me, though. However, `cat -v` shows that it is using bracketed paste mode.

**Comment by cswank** [comment]
I have this problem and I don't use tmux.  It happens when I copy from iterm2 (copying a git commit hash from "git log" and paste back into iterm2.

I get:
00~d2e1719eeeaf4dd806aa82d9c383139708947d1501~
Should be:
d2e1719eeeaf4dd806aa82d9c383139708947d15

The hash is colored yellow in git log, so something to do with ansi color escapes?

**Comment by Oscarteg** [comment]
@cswank I have the same problem. Do you have a solution?

**Comment by kxxoling** [comment]
@jseakle This works, but still no idea why. Can you give a simple explanation?

**Comment by papertigers** [comment]
Is everyone here seeing this specifically with iterm2? We should probably open an issue there if that's the case.

**Comment by ricard0ff** [comment]
for me it happens mostly when opening nested tmux sessions.

**Comment by malvee** [comment]
Happens to me as well, usually just cmd+Q and then reopening iterm2 fixes it. Doesn't happen too often, or else I will just switch to normal terminal

**Comment by koustuvsinha** [comment]
happening to me also, after the latest iterm update

**Comment by imoverclocked** [comment]
@papertigers yes, I do withut tmux/screen when I log into a remote node that doesn't know what bracketed paste is. Pasting into vim is extra annoying there ;)

**Comment by tachim** [comment]
Ugh I'm running into this too. Copy-pasting "n" pastes "0~n1~" instead.

**Comment by sirswa** [comment]
having same issue
copy
40c300b4-7a59-4c3d-91fa-99023bd80208
and paste.. string becomes
00~40c300b4-7a59-4c3d-91fa-99023bd8020801~

iterm build 3.0.13

exit and reopening iterm2 terminal fixes it.

**Comment by yangsu** [comment]
@jseakle's solution is correct. For the curious, this is because somehow you got dropped into bracketed paste mode. See [@ChrisJohnsen's detailed explanation above](#issuecomment-55942439)

**Comment by lakamsani** [comment]
Hi, this is happening to me now after moving to a new macbook laptop (old one is with Apple getting keyboard repaired). I 'm using iTerm2 as well but decided to test with macOS Sierra built-in terminal and it happens there too with vim. So I suspect the issue is with some vim setup and may be a mac OS update. For me it puts `[200~Python[201~` (Python is the string being copied) if I paste in insert mode. It does not do that if I paste without going to insert mode. So that is a bit of a workaround.  `printf '\e[?2004l'` is not fixing it. It does not occur if I do `vim -u NONE`. So something in my `.vimrc` is causing it.  I will experiment a bit by disabling stuff in `.vimrc`. It is consistent and always happens. So very much reproducible.

**Comment by lakamsani** [comment]
I got rid of this problem by commenting out a couple of lines from my vimrc. Details are here.  https://github.com/johndgiese/dotvim/issues/4

**Comment by townhouse** [comment]
Fixed this by adding `set t_BE=` to `.vimrc` to disable bracketed paste mode.

As per: https://gitlab.com/gnachman/iterm2/issues/5698

**Comment by cosven** [comment]
put this in bashrc or any shell rcfile seems the easiest way to disable  `bracketed paste mode`.
```
bind 'set-enable-bracketed-paste off'
```

**Comment by Ninpo** [comment]
Chiming in to say this reliably happens to me when:

I'm ssh'ed to a remote server
I have tmux running on that remote server
Inside tmux I am ssh'ed onto yet another remote server
My PC goes to sleep
After waking the PC up, ssh sessions are abnormally terminated.

Additionally, if I terminate the remote ssh session, pasting into my LOCAL terminal (which is konsole btw) is fine, if I ssh back into the remote again, I get the same bracketed paste prefix/suffix until I run the printf command listed earlier in the thread.

**Comment by kgerickson** [comment]
This happens to me right now after a recent iterm2 update.  No tmux or ssh involved.

**Comment by neverforgit** [comment]
I am getting `0~ ....1~`, e.g.:

`0~SOMETHING_1~`

OS X: 10.12.6
ssh'd into Debian

I cannot consistently recreated this behavior..

**Comment by michi88** [comment]
I think this helped for me:

> Go to iTerm Preferences → Profiles, select your profile, then the Keys tab. Click Load Preset... and choose Natural Text Editing.

from https://apple.stackexchange.com/questions/136928/using-alt-cmd-right-left-arrow-in-iterm

**Comment by teeberg** [comment]
I seem to have been able to fix it by just running `reset`

**Comment by xeor** [comment]
I am getting the same behavior, on Windows, using kitty (putty-like), and tmux..
But only inside 1 tile in my tmux session.. I created another tile in the same tmux window, and pasting the same thing in there works fine.. `reset` doesnt do anything..

`0~PASTED DATA1~`

It is strange.. Because whatever I try to paste into that little window now ends up with those extra characters.. Leaving it open if anyone have anything I can check inside it to figure this out..

**Comment by kalyanac** [comment]
I have the same problem, but only for local terminals. I use a different profile for remote Linux machines and dont have a problem there. Running "reset" fixed it. 

iTerm2 
Build 3.2.7

**Comment by asaunders-allyDVM** [comment]
I can replicate this issue, however it seems to be unrelated to iTerm or TMUX, when using AWS Session Manager to login to an instance from iTerm2 anything I paste into a connected session has a 0~ and 1~  bracketing it. The answer is terminal is in bracketed paste mode. [[https://cirw.in/blog/bracketed-paste]] you can disable bracketed paste mode with ```printf "\e[?2004l```

**Comment by Tasselmi** [comment]
fuck
I have the same problem.
mac iterm2
```
0~property.put1~
```
what the fuck is this `0~` and `1~`
