### ISSUE TITLE
Way to ignore this script if not on OS X?

### ISSUE THREAD

**Issue by tylerball** [ChrisJohnsen/tmux-MacOSX-pasteboard#8]
I like to keep my ~/.tmux.conf consistent across OS X and Linux. Currently the script is not present on my Linux machines and so tmux crashes if the reattach-to-user-namespace command is added. Are you aware of any solution to this problem?

**Comment by blandinw** [comment]
To avoid having an external file, I ended up doing:
```
set -g default-command "which reattach-to-user-namespace 2>/dev/null && reattach-to-user-namespace -l zsh || zsh"
```
This seems to combine the best of both worlds, did I miss something?

**Comment by ChrisJohnsen** [comment]
@blandinw That is almost the same construction as [one of the comments above](#issuecomment-26933900), so it has the same [minor issue](#issuecomment-27129074). The middle part could be written as `&& { … ; true ; } ||` to avoid that issue (at least in this context, since the interactive shell’s exit code is otherwise mostly ignored anyway).

Otherwise, it is a reasonable solution. But, if all your OS X systems are running Yosemite, you may not even need the wrapper anymore: Apple seems to have integrated its own workaround so that the pasteboard remains accessible inside *tmux* sessions.

**Comment by supermarin** [comment]
There's a way that should work without `if-shell` with pure bash:

``` conf
run '[ $(uname) = "Darwin" ] && tmux source ~/.tmux-osx.conf`
```
